import type { FormConfigData } from "@/lib/forms/types";

/**
 * Defaults compartidos para los dos formularios del sistema.
 *
 * Estas constantes eran locales a `components/dashboard/client-profile/tabs/
 * forms-tab.tsx` y se usaban como fallback cuando un cliente no tenía
 * `client_form_configs` propio. Se han extraído aquí para poder reutilizarlas
 * también al auto-crear una plantilla de tenant (`form_templates`) cuando el
 * tenant nunca tuvo una — ver `app/trainer/settings/forms/[formType]/page.tsx`
 * y `app/api/clients/create/route.ts`. Mantener aquí para evitar divergencia
 * entre "defaults del cliente" y "defaults de la plantilla".
 */

export const DEFAULT_CHECKIN_CONFIG: FormConfigData = {
  pages: [
    {
      id: "checkin_reflection",
      title: "Reflexión Personal",
      icon: "solar:user-heart-bold",
      order: 0,
    },
    {
      id: "checkin_goals",
      title: "Objetivos",
      icon: "solar:target-bold",
      order: 1,
    },
    {
      id: "checkin_service",
      title: "Valoración del Servicio",
      icon: "solar:star-bold",
      order: 2,
    },
    {
      id: "checkin_body",
      title: "Fotos y Medidas",
      icon: "solar:camera-bold",
      order: 3,
    },
  ],
  questions: [
    // ── Page: Reflexión Personal ──
    {
      id: "personal_life",
      label: "Vida Personal",
      fullQuestion: "¿Cómo va todo a nivel personal?",
      icon: "solar:user-heart-bold",
      type: "text",
      enabled: true,
      required: true,
      pageId: "checkin_reflection",
    },
    {
      id: "gym_achievement",
      label: "Triunfo en el Gimnasio",
      fullQuestion:
        "Triunfo que has conseguido en el gimnasio desde última revisión",
      icon: "solar:cup-star-bold",
      type: "text",
      enabled: true,
      required: true,
      pageId: "checkin_reflection",
    },
    {
      id: "other_victory",
      label: "Otra Victoria",
      fullQuestion: "¿Alguna otra victoria que celebrar?",
      icon: "solar:star-circle-bold",
      type: "text",
      enabled: true,
      required: false,
      pageId: "checkin_reflection",
    },
    {
      id: "biggest_challenge",
      label: "Mayor Desafío",
      fullQuestion: "¿Cuál ha sido el mayor desafío al que te has enfrentado?",
      icon: "solar:shield-warning-bold",
      type: "text",
      enabled: true,
      required: true,
      pageId: "checkin_reflection",
    },
    // ── Page: Objetivos ──
    {
      id: "goals_completed",
      label: "Objetivos Cumplidos",
      fullQuestion:
        "¿Has cumplido objetivos que te marcaste en nuestra última revisión?",
      icon: "solar:check-square-bold",
      type: "boolean",
      enabled: true,
      required: true,
      pageId: "checkin_goals",
    },
    {
      id: "goals_impediment",
      label: "Impedimentos",
      fullQuestion: "¿Qué te lo ha impedido?",
      icon: "solar:close-circle-bold",
      type: "text",
      enabled: true,
      required: false,
      conditionalOn: "goals_completed",
      conditionalValue: false,
      pageId: "checkin_goals",
    },
    {
      id: "focus_next_weeks",
      label: "Enfoque Próximas Semanas",
      fullQuestion:
        "¿En qué quieres enfocarte especialmente para mejorar en estas próximas semanas?",
      icon: "solar:target-bold",
      type: "text",
      enabled: true,
      required: true,
      pageId: "checkin_goals",
    },
    // ── Page: Valoración del Servicio ──
    {
      id: "service_rating",
      label: "Valoración del Servicio",
      fullQuestion: "¿Cómo valoras el servicio que te estamos dando?",
      icon: "solar:star-bold",
      type: "rating",
      enabled: true,
      required: true,
      pageId: "checkin_service",
    },
    {
      id: "service_details",
      label: "Detalles del Servicio",
      fullQuestion: "¿Me puedes dar más detalles?",
      icon: "solar:chat-round-dots-bold",
      type: "text",
      enabled: true,
      required: false,
      conditionalOn: "service_rating",
      conditionalValue: true,
      pageId: "checkin_service",
    },
    // ── Page: Fotos y Medidas ──
    {
      id: "photos",
      label: "Fotos de Progreso",
      icon: "solar:camera-bold",
      type: "group",
      enabled: true,
      required: false,
      pageId: "checkin_body",
      subQuestions: [
        {
          id: "photo_front",
          label: "Foto de Frente",
          icon: "solar:user-bold",
          type: "photo",
          enabled: true,
          required: false,
        },
        {
          id: "photo_side",
          label: "Foto de Perfil",
          icon: "solar:user-bold",
          type: "photo",
          enabled: true,
          required: false,
        },
        {
          id: "photo_back",
          label: "Foto de Espaldas",
          icon: "solar:user-bold",
          type: "photo",
          enabled: true,
          required: false,
        },
      ],
    },
    {
      id: "body_measurements",
      label: "Medidas Corporales",
      icon: "solar:ruler-bold",
      type: "group",
      enabled: true,
      required: false,
      pageId: "checkin_body",
      subQuestions: [
        {
          id: "chest",
          label: "Pecho",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "shoulders",
          label: "Hombros",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "arm",
          label: "Brazo",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "above_navel",
          label: "Sobre el Ombligo 3cm",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "below_navel",
          label: "Bajo el Ombligo 3cm",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "groin",
          label: "Ingle",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "thigh",
          label: "Muslo",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
        {
          id: "calf",
          label: "Gemelo",
          icon: "solar:ruler-cross-pen-bold",
          type: "number",
          unit: "cm",
          enabled: true,
          required: false,
        },
      ],
    },
    {
      // Optional by default: many clients don't have a scale on every
      // check-in day. Trainers who insist on body weight can toggle this
      // back to required from /trainer/settings/forms/checkins.
      id: "body_weight",
      label: "Peso Corporal",
      icon: "solar:scale-bold",
      type: "number",
      unit: "kg",
      enabled: true,
      required: false,
      pageId: "checkin_body",
    },
  ],
};

export const DEFAULT_HABIT_CONFIG: FormConfigData = {
  pages: [
    {
      id: "habit_wellbeing",
      title: "Bienestar",
      icon: "solar:heart-pulse-bold",
      order: 0,
    },
    {
      id: "habit_activity",
      title: "Actividad Física",
      icon: "solar:running-bold",
      order: 1,
    },
    {
      id: "habit_nutrition",
      title: "Nutrición",
      icon: "solar:plate-bold",
      order: 2,
    },
    {
      id: "habit_sleep",
      title: "Sueño",
      icon: "solar:sleeping-bold",
      order: 3,
    },
  ],
  questions: [
    // ── Page: Bienestar ──
    {
      id: "body_weight",
      label: "Peso Corporal",
      fullQuestion: "¿Cuánto pesas hoy?",
      icon: "solar:scale-bold",
      type: "number",
      unit: "kg",
      enabled: true,
      required: false,
      pageId: "habit_wellbeing",
    },
    {
      id: "energy_levels",
      label: "Niveles de Energía",
      fullQuestion: "Niveles de energía durante el día",
      icon: "solar:bolt-bold",
      type: "rating",
      enabled: true,
      required: false,
      pageId: "habit_wellbeing",
    },
    {
      id: "stress_levels",
      label: "Manejo del Estrés",
      fullQuestion: "¿Qué tal has sobrellevado el estrés?",
      icon: "solar:shield-warning-bold",
      type: "rating",
      enabled: true,
      required: false,
      pageId: "habit_wellbeing",
    },
    {
      id: "illness_signs",
      label: "Signos de Enfermedad",
      fullQuestion: "¿Has tenido algún signo de enfermedad, infección, dolor?",
      icon: "solar:health-bold",
      type: "boolean",
      enabled: true,
      required: false,
      pageId: "habit_wellbeing",
    },
    {
      id: "illness_details",
      label: "Detalles de Enfermedad",
      fullQuestion: "Más detalles",
      icon: "solar:notes-bold",
      type: "text",
      enabled: true,
      required: false,
      conditionalOn: "illness_signs",
      conditionalValue: true,
      pageId: "habit_wellbeing",
    },
    // ── Page: Actividad Física ──
    {
      id: "steps",
      label: "Pasos del Día",
      fullQuestion: "¿Cuántos pasos has hecho hoy?",
      icon: "solar:walking-bold",
      type: "number",
      unit: "pasos",
      enabled: true,
      required: false,
      pageId: "habit_activity",
    },
    {
      id: "other_activity",
      label: "Otra Actividad Física",
      fullQuestion: "¿Otra actividad física exigente?",
      icon: "solar:running-bold",
      type: "boolean",
      enabled: true,
      required: false,
      pageId: "habit_activity",
    },
    {
      id: "other_activity_details",
      label: "Detalles de Actividad",
      fullQuestion: "Más detalles",
      icon: "solar:notes-bold",
      type: "text",
      enabled: true,
      required: false,
      conditionalOn: "other_activity",
      conditionalValue: true,
      pageId: "habit_activity",
    },
    {
      id: "sun_exposure",
      label: "Exposición Solar",
      fullQuestion: "Horas de exposición al sol durante el día",
      icon: "solar:sun-bold",
      type: "number",
      unit: "horas",
      enabled: true,
      required: false,
      pageId: "habit_activity",
    },
    // ── Page: Nutrición ──
    {
      id: "macro_tracking",
      label: "Seguimiento de Macros",
      fullQuestion: "¿Seguimiento de macros hoy?",
      icon: "solar:pie-chart-bold",
      type: "group",
      enabled: true,
      required: false,
      pageId: "habit_nutrition",
      subQuestions: [
        {
          id: "calories",
          label: "Calorías Totales",
          icon: "solar:fire-bold",
          type: "number",
          unit: "kcal",
          enabled: true,
          required: false,
        },
        {
          id: "protein",
          label: "Proteína",
          icon: "solar:bone-bold",
          type: "number",
          unit: "g",
          enabled: true,
          required: false,
        },
        {
          id: "carbs",
          label: "Carbohidratos",
          icon: "solar:leaf-bold",
          type: "number",
          unit: "g",
          enabled: true,
          required: false,
        },
        {
          id: "fats",
          label: "Grasas",
          icon: "solar:cloud-waterdrop-bold",
          type: "number",
          unit: "g",
          enabled: true,
          required: false,
        },
      ],
    },
    {
      id: "hunger_levels",
      label: "Niveles de Hambre",
      fullQuestion: "¿Cómo han sido tus niveles de hambre?",
      icon: "solar:plate-bold",
      type: "rating",
      enabled: true,
      required: false,
      pageId: "habit_nutrition",
    },
    {
      id: "adherence",
      label: "Adherencia al Plan",
      fullQuestion: "¿Cómo ha sido la adherencia?",
      icon: "solar:check-circle-bold",
      type: "rating",
      enabled: true,
      required: false,
      pageId: "habit_nutrition",
    },
    {
      id: "adherence_reason",
      label: "Razón de No Adherencia",
      fullQuestion: "¿Por qué no te has podido ceñir al plan?",
      icon: "solar:question-circle-bold",
      type: "text",
      enabled: true,
      required: false,
      conditionalOn: "adherence",
      conditionalValue: true,
      pageId: "habit_nutrition",
    },
    {
      id: "caffeine",
      label: "Consumo de Cafeína",
      fullQuestion: "¿Cuánta cafeína se ha consumido?",
      icon: "solar:cup-hot-bold",
      type: "number",
      unit: "mg",
      enabled: true,
      required: false,
      pageId: "habit_nutrition",
    },
    {
      id: "supplementation",
      label: "Suplementación",
      fullQuestion: "Suplementación",
      icon: "solar:pill-bold",
      type: "text",
      enabled: true,
      required: false,
      pageId: "habit_nutrition",
    },
    // ── Page: Sueño ──
    {
      id: "bedtime",
      label: "Hora de Acostar",
      fullQuestion: "¿A qué hora te acostaste ayer?",
      icon: "solar:moon-stars-bold",
      type: "text",
      enabled: true,
      required: false,
      pageId: "habit_sleep",
    },
    {
      id: "wake_time",
      label: "Hora de Despertar",
      fullQuestion: "¿A qué hora te has despertado hoy?",
      icon: "solar:sun-fog-bold",
      type: "text",
      enabled: true,
      required: false,
      pageId: "habit_sleep",
    },
    {
      id: "sleep_hours",
      label: "Horas de Sueño",
      fullQuestion: "¿Cuántas horas has dormido en total?",
      icon: "solar:sleeping-bold",
      type: "number",
      unit: "horas",
      enabled: true,
      required: false,
      pageId: "habit_sleep",
    },
    {
      id: "morning_feeling",
      label: "Sensación al Despertar",
      fullQuestion: "Al salir de cama esta mañana sentías que",
      icon: "solar:smile-circle-bold",
      type: "rating",
      enabled: true,
      required: false,
      pageId: "habit_sleep",
    },
    {
      id: "morning_feeling_details",
      label: "Detalles de Despertar",
      fullQuestion: "Más detalles",
      icon: "solar:notes-bold",
      type: "text",
      enabled: true,
      required: false,
      conditionalOn: "morning_feeling",
      conditionalValue: true,
      pageId: "habit_sleep",
    },
    {
      id: "special_comment",
      label: "Comentario Especial",
      fullQuestion: "Comentario especial",
      icon: "solar:chat-round-dots-bold",
      type: "boolean",
      enabled: false,
      required: false,
      pageId: "habit_sleep",
    },
  ],
};
